spring:
    main:
        banner-mode: "off"
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/nfe
        username: root
        password: root
arquivei:
    api:
        url: https://sandbox-api.arquivei.com.br/v1/nfe/received
        x-api-id: f96ae22f7c5d74fa4d78e764563d52811570588e
        x-api-key: cc79ee9464257c9e1901703e04ac9f86b0f387c2
        cursor: 0
        limit: 5
